@section('styles')
<style>
    /* Important part */
    .modal-dialog {
        overflow-y: initial !important
    }

    .modal-body {
        height: 80vh;
        overflow-y: auto;
    }
    .modal-body li {
        margin-bottom: 10px;
    }
</style>
@endsection
<!-- Edit Modal -->
<div class="modal fade d-none" id="terms_and_condition" aria-hidden="true" role="dialog" data-bs-keyboard="false" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content rounded-4 border-2">
            <div class="modal-body pb-0">
                <div class="form-content p-2">
                    <div class="modal-header border-0 ps-0 pt-0">
                        <h4 class="modal-title border-bottom-3">Terms & Conditions</h4>
                    </div>
                    <div class="card mb-0" style="max-height:50vh; overflow-y: scroll;overflow-x: hidden;">
                        <div class="card-body">
                            <div class="row">
                                <ul>
                                    <li>NEET Navigator Educational Services is a private business entity incorporated as sole proprietor firm in 2022 registered at New Delhi. NEET Navigator is in service business of providing consultancy and advisory services mainly related to education, counselling and medical admissions.</li>
                                    <li>NEET Navigator Educational Services has NO liaison with any medical college or management of any medical college. NEET Navigator Educational Services is NOT a government agency and doesn’t make any claim of influence on any counselling process.</li>
                                    <li>NEET Navigator Educational Services is represented in market place through two service names, NEET Navigator and MBBS Lighthouse. NEET Navigator Educational Services has already filed for trademark registration of these services.</li>
                                    <li>NEET Navigator owns an online web application MBBS Lighthouse which is an advanced data analytics based medical admission possibility predictor. MBBS Lighthouse is an online service offering of NEET Navigator.</li>
                                    <li>MBBS Lighthouse is designed on historical medical admission data. For 2023 predictions, MBBS Lighthouse analyzes counselling data of year 2022. All the analytical reports are technology driven and based on entered user data.</li>
                                    <li>MBBS Lighthouse is currently developed on admission counselling data of MCC and 32 Indian states. The analytics and reports are auto-calculated on the basis of user data including NEET score, domicile, category and fee budget etc.</li>
                                    <li>The user data is stored in the encrypted formats and no person or agency including NEET Navigator has access to modify or delete the user’s data. The user data and credentials are stored on secured Google cloud servers.</li>
                                    <li>MBBS Lighthouse offers customized reports and analytics based on a specific user’s credentials such as domicile, category and NEET score. The reports and analytics are not generalized. Therefore, generated report content is not applicable to any other applicant.</li>
                                    <li>The reports and analytics of MBBS Lighthouse shall be used only as one input for planning of admission strategy. MBBS Lighthouse does not claim or offer any directions for medical admission counselling process.</li>
                                    <li>MBBS Lighthouse or NEET Navigator shall not be responsible for any loss of opportunity due to any of the reports and analytics. The user is advised to apply due diligence on the analysis of reports generated by MBBS Lighthouse.</li>
                                    <li>MBBS Lighthouse, at present, estimates the admission possibility in MBBS for 646 medical colleges. NEET Navigator is making continuous efforts to incorporate the admission data of remaining medical colleges and other courses as well.</li>
                                    <li>MBBS Lighthouse is designed on curated data of medical admissions. It is practically impossible to access and incorporate all the data entries into the application. MBBS Lighthouse is curated to include approx 90% of admission counselling data for 2022.</li>
                                    <li>MBBS Lighthouse reports and predictions shall be considered as indicative and not final. The reports are directional in nature. NEET Navigator or MBBS Lighthouse claims no guarantee or assurance of medical admission.</li>
                                    <li>Use of NEET Navigator and MBBS Lighthouse is completely voluntary in nature. NEET Navigator Educational Services ensures due diligence in all the promotional communications. However, any reference to threat, fear or coercion is unintentional and inadvertent. NEET Navigator Educational Services shall not be liable for any such action.</li>
                                </ul>
                            </div>
                            <div class="text-end">
                                <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal">AGREE</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Edit Modal -->