<link rel="stylesheet" href="{{ asset('assets/home/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/fontawesome-all.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/jquery.fancybox.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/jquery.mCustomScrollbar.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/odometer-theme-default.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets/home/css/style.css') }}">